core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', include('excursions.urls', namespace='excursions')),
    path('contacts', contacts, name='contacts'),
    path('t/', include('tailwind.urls', namespace='tailwind')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT, )


admin.site.index_title = 'Админка'
admin.site.site_header = 'Я-Евпатория!'
admin.site.site_title = 'Я-Евпатория!'

excursions/urls.py
from django.urls import path
from .views import *

app_name = 'excursions'

urlpatterns = [
    path('', HomeExcursions.as_view(), name='home'),
]

tailwind/urls.py
from django.urls import path
from .views import *

app_name = 'tailwind'

urlpatterns = [
    path('', tailwind_home),
    path('tmp/sidenav-scrimba/', sidenav_scrimba),
    path('navbars/dark_with_quick_action/', navbars_dark_with_quick_action),
    path('navbars/dark_with_search/', navbars_dark_with_search),
    path('navbars/simple/', navbars_simple),
    path('navbars/simple_dark_with_menu_button_on_left/', navbars_simple_dark_with_menu_button_on_left),
    path('navbars/simple_dark/', navbars_simple_dark),
    path('navbars/simple_with_menu_button_on_left/', navbars_simple_with_menu_button_on_left),
    path('navbars/with_centered_search_and_secondary_links_dark/', navbars_with_centered_search_and_secondary_links_dark),
    path('navbars/with_centered_search_and_secondary_links/', navbars_with_centered_search_and_secondary_links),
    path('navbars/with_search_in_column_layout/', navbars_with_search_in_column_layout),
    path('navbars/with_search/', navbars_with_search),
]

excursions/models.py
from django.db import models


class Exscursion(models.Model):
    TYPES = (
        ('group', 'Групповая'),
        ('individual', 'Индивидуальная'),
    )

    name = models.CharField(max_length=255, verbose_name='Название экскурсии')
    description = models.TextField(blank=True, verbose_name='Описание')
    location = models.CharField(max_length=255, verbose_name='Локация', null=True, blank=True)
    duration = models.CharField(max_length=255, verbose_name='Длительность', null=True, blank=True)
    max_people_count = models.CharField(max_length=255, verbose_name='Кол-во человек', null=True, blank=True)
    price = models.CharField(max_length=255, verbose_name='Стоимость', null=True, blank=True)
    photo = models.ImageField(upload_to='excursions_photos', verbose_name='Фото', null=True, blank=True)
    type = models.CharField(max_length=10, choices=TYPES, verbose_name='Тип', default='group')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Экскурсию'
        verbose_name_plural = 'Экскурсии'
        ordering = ['-created_at']

core/views.py
from django.shortcuts import render


def contacts(request):
    return render(request, 'contacts.html', {'section': 'contacts'})

excursions/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Exscursion


def home(request):
    return render(request, 'excursions/index.html', {'section': 'excursions'})


class HomeExcursions(ListView):
    model = Exscursion
    template_name = 'excursions/index.html'
    context_object_name = 'excursions'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'excursions'
        return context

tailwind/views.py
from django.shortcuts import render


def tailwind_home(request):
    return render(request, 'tailwind/main.html')


def sidenav_scrimba(request):
    return render(request, 'tailwind/tmp/sidenav-scrimba.html')


def navbars_dark_with_quick_action(request):
    return render(request, 'tailwind/navbars/dark_with_quick_action.html')


def navbars_dark_with_search(request):
    return render(request, 'tailwind/navbars/dark_with_search.html')


def navbars_simple(request):
    return render(request, 'tailwind/navbars/simple.html')


def navbars_simple_dark_with_menu_button_on_left(request):
    return render(request, 'tailwind/navbars/simple_dark_with_menu_button_on_left.html')


def navbars_simple_dark(request):
    return render(request, 'tailwind/navbars/simple_dark.html')


def navbars_simple_with_menu_button_on_left(request):
    return render(request, 'tailwind/navbars/simple_with_menu_button_on_left.html')


def navbars_with_centered_search_and_secondary_links_dark(request):
    return render(request, 'tailwind/navbars/with_centered_search_and_secondary_links_dark.html')


def navbars_with_centered_search_and_secondary_links(request):
    return render(request, 'tailwind/navbars/with_centered_search_and_secondary_links.html')


def navbars_with_quick_action(request):
    return render(request, 'tailwind/navbars/with_quick_action.html')


def navbars_with_search_in_column_layout(request):
    return render(request, 'tailwind/navbars/with_search_in_column_layout.html')


def navbars_with_search(request):
    return render(request, 'tailwind/navbars/with_search.html')

tailwind/templates/tailwind/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <script src="{% static 'js/app.js' %}" defer></script>
    <title>Title</title>
</head>

<body class="antialiased font-sans">

{% block content %}{% endblock content %}

</body>

</html>

tailwind/templates/tailwind/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <script src="{% static 'js/app.js' %}" defer></script>
    <title>Я-Евпатория!</title>
</head>

<body class="antialiased font-sans bg-gray-100">

    <nav x-data="{ open: false }" class="bg-white shadow">
        <div class="max-w-full mx-auto px-2 sm:px-4 lg:px-8">
            <div class="flex justify-between h-16">
                <div class="flex px-2 lg:px-0">
                    <div class="flex-shrink-0 flex items-center">
                        <img class="block lg:hidden h-10 w-auto" src="{% static 'img/Я-Евпатория!.svg' %}"
                            alt="Workflow">
                        <img class="hidden lg:block h-12 w-auto" src="{% static 'img/Я-Евпатория!.svg' %}"
                            alt="Workflow">
                    </div>
                    <div class="hidden lg:ml-6 lg:flex lg:space-x-8">
                        <!-- Current: "border-amber-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
                        <a href="#"
                            class="border-amber-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                            Экскурсии
                        </a>
                        <a href="#"
                            class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                            Контакты
                        </a>
                    </div>
                </div>
                <div class="flex-1 flex items-center justify-center px-2 lg:ml-6 lg:justify-end">
                    <div class="max-w-lg w-full lg:max-w-xs">
                        <label for="search" class="sr-only">Поиск</label>
                        <div class="relative">
                            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                <svg class="h-5 w-5 text-gray-400" x-description="Heroicon name: solid/search"
                                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                    aria-hidden="true">
                                    <path fill-rule="evenodd"
                                        d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                        clip-rule="evenodd"></path>
                                </svg>
                            </div>
                            <input id="search" name="search"
                                class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-amber-500 focus:border-amber-500 sm:text-sm"
                                placeholder="Поиск" type="search">
                        </div>
                    </div>
                </div>
                <div class="flex items-center lg:hidden">
                    <!-- Mobile menu button -->
                    <button type="button"
                        class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-amber-500"
                        aria-controls="mobile-menu" @click="open = !open" aria-expanded="false"
                        x-bind:aria-expanded="open.toString()">
                        <span class="sr-only">Открыть меню</span>
                        <svg x-description="Icon when menu is closed.

Heroicon name: outline/menu" x-state:on="Menu open" x-state:off="Menu closed" class="block h-6 w-6"
                            :class="{ 'hidden': open, 'block': !(open) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4 6h16M4 12h16M4 18h16"></path>
                        </svg>
                        <svg x-description="Icon when menu is open.

Heroicon name: outline/x" x-state:on="Menu open" x-state:off="Menu closed" class="hidden h-6 w-6"
                            :class="{ 'block': open, 'hidden': !(open) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                    </button>
                </div>
                <div class="hidden lg:ml-4 lg:flex lg:items-center">
                    <button
                        class="flex-shrink-0 bg-white p-1 text-gray-400 rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500">
                        <span class="sr-only">Избранное</span>
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
                            </path>
                        </svg>
                    </button>

                    <!-- Profile dropdown -->
                    <div x-data="{ open: false }" @keydown.escape.stop="open = false" @click.away="open = false"
                        class="ml-4 relative flex-shrink-0">
                        <div>
                            <button type="button"
                                class="bg-white rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500"
                                id="user-menu" aria-expanded="false" @click="open = !open" aria-haspopup="true"
                                x-bind:aria-expanded="open">
                                <span class="sr-only">Меню пользователя</span>
                                <img class="h-8 w-8 rounded-full"
                                    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&amp;ixqx=cII20c177f&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80"
                                    alt="">
                            </button>
                        </div>

                        <transition enter-active-class="transition ease-out duration-100"
                            enter-class="transform opacity-0 scale-95" enter-to-class="transform opacity-100 scale-100"
                            leave-active-class="transition ease-in duration-75"
                            leave-class="transform opacity-100 scale-100" leave-to-class="transform opacity-0 scale-95">
                            <div x-description="Dropdown menu, show/hide based on menu state." x-show="open"
                                class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
                                role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                    role="menuitem">Профиль</a>
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                    role="menuitem">Выйти</a>
                            </div>
                        </transition>

                    </div>
                </div>
            </div>
        </div>

        <div x-description="Mobile menu, show/hide based on menu state." class="lg:hidden" id="mobile-menu"
            x-show="open">
            <div class="pt-2 pb-3 space-y-1">
                <!-- Current: "bg-amber-50 border-amber-500 text-amber-700", Default: "border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800" -->
                <a href="#"
                    class="bg-amber-50 border-amber-500 text-amber-600 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Экскурсии</a>
                <a href="#"
                    class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Контакты</a>
            </div>
            <div class="pt-4 pb-3 border-t border-gray-200">
                <div class="flex items-center px-4">
                    <div class="flex-shrink-0">
                        <img class="h-10 w-10 rounded-full"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&amp;ixqx=cII20c177f&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80"
                            alt="">
                    </div>
                    <div class="ml-3">
                        <div class="text-base font-medium text-gray-800">Том Кук</div>
                        <div class="text-sm font-medium text-gray-500">tom@example.com</div>
                    </div>
                    <button
                        class="ml-auto flex-shrink-0 bg-white p-1 text-gray-400 rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500">
                        <span class="sr-only">Избранное</span>
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
                            </path>
                        </svg>
                    </button>
                </div>
                <div class="mt-3 space-y-1">
                    <a href="#"
                        class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">Профиль</a>
                    <a href="#"
                        class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">Выйти</a>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock content %}

</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <script src="{% static 'js/app.js' %}" defer></script>
    <title>{% block title %}{% endblock title %}Я-Евпатория!</title>
</head>

<body class="antialiased font-sans bg-gray-100">

    {% include 'partials/navbar.html' %}

    {% block content %}{% endblock content %}

</body>

</html>

templates/contacts.html
{% extends 'base.html' %}

{% block title %}Контактная информация | {% endblock title %}

{% block content %}

<div class="max-w-full mx-auto px-2 sm:px-4 lg:px-8">

    <h1 class="text-4xl font-normal mt-6 text-gray-700">Контактная информация</h1>

</div>

{% endblock content %}

templates/partials/navbar.html
<nav x-data="{ open: false }" class="bg-white shadow">
    <div class="max-w-full mx-auto px-2 sm:px-4 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex px-2 lg:px-0">
                <div class="flex-shrink-0 flex items-center">
                    {% if section == "excursions" %}
                    <img class="block h-10 lg:h-12 w-auto" src="/media/img/Я-Евпатория!.svg" alt="Workflow">
                    {% else %}
                    <a href="{% url 'excursions:home' %}"><img class="block h-10 lg:h-12 w-auto" src="/media/img/Я-Евпатория!.svg" alt="Workflow"></a>
                    {% endif %}
                </div>
                <div class="hidden lg:ml-6 lg:flex lg:space-x-8">
                    <!-- Current: "border-amber-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
                    <a href="{% url 'excursions:home' %}"
                        class="{% if section == "excursions" %} border-amber-500 text-gray-900 {% else %} border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 {% endif %} inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                        Экскурсии
                    </a>
                    <a href="{% url 'contacts' %}"
                        class="{% if section == "contacts" %} border-amber-500 text-gray-900 {% else %} border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 {% endif %} inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                        Контактная информация
                    </a>
                </div>
            </div>
            <div class="flex-1 flex items-center justify-center px-2 lg:ml-6 lg:justify-end">
                <div class="max-w-lg w-full lg:max-w-xs">
                    <label for="search" class="sr-only">Поиск</label>
                    <div class="relative">
                        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                            <svg class="h-5 w-5 text-gray-400" x-description="Heroicon name: solid/search"
                                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                aria-hidden="true">
                                <path fill-rule="evenodd"
                                    d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                    clip-rule="evenodd"></path>
                            </svg>
                        </div>
                        <input id="search" name="search"
                            class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-amber-500 focus:border-amber-500 sm:text-sm"
                            placeholder="Поиск" type="search">
                    </div>
                </div>
            </div>
            <div class="flex items-center lg:hidden">
                <!-- Mobile menu button -->
                <button type="button"
                    class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-amber-500"
                    aria-controls="mobile-menu" @click="open = !open" aria-expanded="false"
                    x-bind:aria-expanded="open.toString()">
                    <span class="sr-only">Открыть меню</span>
                    <svg x-description="Icon when menu is closed.

Heroicon name: outline/menu" x-state:on="Menu open" x-state:off="Menu closed" class="block h-6 w-6"
                        :class="{ 'hidden': open, 'block': !(open) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                    <svg x-description="Icon when menu is open.

Heroicon name: outline/x" x-state:on="Menu open" x-state:off="Menu closed" class="hidden h-6 w-6"
                        :class="{ 'block': open, 'hidden': !(open) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12">
                        </path>
                    </svg>
                </button>
            </div>
            <div class="hidden lg:ml-4 lg:flex lg:items-center">
                <button
                    class="flex-shrink-0 bg-white p-1 text-gray-400 rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500">
                    <span class="sr-only">Избранное</span>
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
                        </path>
                    </svg>
                </button>

                <!-- Profile dropdown -->
                <div x-data="{ open: false }" @keydown.escape.stop="open = false" @click.away="open = false"
                    class="ml-4 relative flex-shrink-0">
                    <div>
                        <button type="button"
                            class="bg-white rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500"
                            id="user-menu" aria-expanded="false" @click="open = !open" aria-haspopup="true"
                            x-bind:aria-expanded="open">
                            <span class="sr-only">Меню пользователя</span>
                            <img class="h-8 w-8 rounded-full"
                                src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&amp;ixqx=cII20c177f&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80"
                                alt="">
                        </button>
                    </div>

                    <transition enter-active-class="transition ease-out duration-100"
                        enter-class="transform opacity-0 scale-95" enter-to-class="transform opacity-100 scale-100"
                        leave-active-class="transition ease-in duration-75"
                        leave-class="transform opacity-100 scale-100" leave-to-class="transform opacity-0 scale-95">
                        <div x-description="Dropdown menu, show/hide based on menu state." x-show="open"
                            class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
                            role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                role="menuitem">Профиль</a>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                role="menuitem">Выйти</a>
                        </div>
                    </transition>

                </div>
            </div>
        </div>
    </div>

    <div x-description="Mobile menu, show/hide based on menu state." class="lg:hidden" id="mobile-menu" x-show="open">
        <div class="pt-2 pb-3 space-y-1">
            <!-- Current: "bg-amber-50 border-amber-500 text-amber-700", Default: "border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800" -->
            <a href="{% url 'excursions:home' %}"
                class="{% if section == "excursions" %}bg-amber-50 border-amber-500 text-amber-600 {% else %} border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 {% endif %} block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Экскурсии</a>
            <a href="{% url 'contacts' %}"
                class="{% if section == "contacts" %}bg-amber-50 border-amber-500 text-amber-600 {% else %} border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 {% endif %} block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Контакты</a>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <img class="h-10 w-10 rounded-full"
                        src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&amp;ixqx=cII20c177f&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80"
                        alt="">
                </div>
                <div class="ml-3">
                    <div class="text-base font-medium text-gray-800">Том Кук</div>
                    <div class="text-sm font-medium text-gray-500">tom@example.com</div>
                </div>
                <button
                    class="ml-auto flex-shrink-0 bg-white p-1 text-gray-400 rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500">
                    <span class="sr-only">Избранное</span>
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
                        </path>
                    </svg>
                </button>
            </div>
            <div class="mt-3 space-y-1">
                <a href="#"
                    class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">Профиль</a>
                <a href="#"
                    class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">Выйти</a>
            </div>
        </div>
    </div>
</nav>